name: spdx_licenses
description: A Dart library for working with the SPDX License List
version: 0.0.1
homepage: https://github.com/adaptant-labs/spdx-licenses-dart
author: Adaptant Labs <labs@adaptant.io>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  resource: ^2.1.5

dev_dependencies:
  test: ^1.0.0
